-- The catalog's tables as Postgres would hold them: schema.sql in Postgres
-- types, for checking that the catalog's portable SQL prepares on a second
-- backend (issue #341). No release opens a Postgres catalog; this file is
-- kept in step with schema.sql by a test, table by table and column by
-- column. INTEGER is BIGINT (ids are i64), REAL is DOUBLE PRECISION and
-- BLOB is BYTEA; tables whose rows SQLite numbers get an identity column.

CREATE TABLE IF NOT EXISTS sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path TEXT NOT NULL,
    imported_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    original_size BIGINT NOT NULL,
    original_catalog BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS roots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_path TEXT NOT NULL,
    mapped_path TEXT
);

CREATE TABLE IF NOT EXISTS folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    root BIGINT NOT NULL REFERENCES roots(id),
    relative_path TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder BIGINT NOT NULL REFERENCES folders(id),
    filename TEXT NOT NULL,
    original_path TEXT NOT NULL,
    captured TEXT NOT NULL DEFAULT '',
    rating BIGINT NOT NULL DEFAULT 0 CHECK(rating BETWEEN 0 AND 5),
    flag BIGINT NOT NULL DEFAULT 0 CHECK(flag BETWEEN -1 AND 1),
    label TEXT NOT NULL DEFAULT '',
    format TEXT NOT NULL DEFAULT '',
    copy_name TEXT NOT NULL DEFAULT '',
    master_id BIGINT,
    orientation TEXT,
    lightroom_develop TEXT,
    recipe TEXT,
    export_options TEXT,
    identity TEXT,
    edited_at TEXT
);

CREATE INDEX IF NOT EXISTS photos_folder ON photos(folder);

CREATE INDEX IF NOT EXISTS photos_captured ON photos(captured);

CREATE INDEX IF NOT EXISTS photos_master ON photos(master_id);

CREATE TABLE IF NOT EXISTS collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parent BIGINT,
    kind TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS collection_photos (
    collection BIGINT NOT NULL REFERENCES collections(id),
    photo BIGINT NOT NULL REFERENCES photos(id),
    position TEXT,
    PRIMARY KEY(collection,photo)
);

CREATE TABLE IF NOT EXISTS keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    parent BIGINT
);

CREATE TABLE IF NOT EXISTS photo_keywords (
    photo BIGINT NOT NULL REFERENCES photos(id),
    keyword BIGINT NOT NULL REFERENCES keywords(id),
    PRIMARY KEY(photo,keyword)
);

CREATE TABLE IF NOT EXISTS folder_mappings (
    folder BIGINT PRIMARY KEY REFERENCES folders(id),
    path TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lightroom_history (
    photo BIGINT NOT NULL,
    position BIGINT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    created DOUBLE PRECISION,
    text TEXT NOT NULL,
    PRIMARY KEY(photo, position)
);

CREATE TABLE IF NOT EXISTS local_edits (
    photo BIGINT PRIMARY KEY,
    data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS develop_history (
    photo BIGINT PRIMARY KEY REFERENCES photos(id) ON DELETE CASCADE,
    data BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS develop_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo BIGINT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    recipe TEXT,
    lightroom BYTEA
);
CREATE INDEX IF NOT EXISTS develop_snapshots_photo ON develop_snapshots(photo);

CREATE TABLE IF NOT EXISTS bitmaps (
    hash TEXT PRIMARY KEY,
    data BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS photo_info (
    photo BIGINT PRIMARY KEY,
    camera TEXT,
    lens TEXT,
    focal DOUBLE PRECISION,
    aperture DOUBLE PRECISION,
    exposure DOUBLE PRECISION,
    iso DOUBLE PRECISION,
    width BIGINT,
    height BIGINT
);

CREATE TABLE IF NOT EXISTS meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS photo_fields (
    photo BIGINT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    field TEXT NOT NULL,
    state TEXT NOT NULL CHECK(state IN ('set', 'cleared')),
    PRIMARY KEY(photo, field)
);

CREATE TABLE IF NOT EXISTS photo_text (
    photo BIGINT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    field TEXT NOT NULL,
    lang TEXT NOT NULL,
    position BIGINT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY(photo, field, lang)
);

CREATE TABLE IF NOT EXISTS photo_creators (
    photo BIGINT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    position BIGINT NOT NULL,
    name TEXT NOT NULL,
    PRIMARY KEY(photo, position)
);

CREATE TABLE IF NOT EXISTS photo_capture (
    photo BIGINT PRIMARY KEY REFERENCES photos(id) ON DELETE CASCADE,
    captured TEXT NOT NULL,
    subsec TEXT,
    "offset" TEXT
);

CREATE TABLE IF NOT EXISTS photo_location (
    photo BIGINT PRIMARY KEY REFERENCES photos(id) ON DELETE CASCADE,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    alt DOUBLE PRECISION,
    cleared BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS keywords_parent_name ON keywords(parent, name);

CREATE TABLE IF NOT EXISTS keyword_export (
    keyword BIGINT PRIMARY KEY REFERENCES keywords(id) ON DELETE CASCADE,
    include BIGINT NOT NULL,
    parents BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS computers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    adopted_at TEXT
);

CREATE TABLE IF NOT EXISTS folder_paths (
    folder BIGINT PRIMARY KEY REFERENCES folders(id) ON DELETE CASCADE,
    path TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS folder_paths_path ON folder_paths(path);

CREATE TABLE IF NOT EXISTS folder_locations (
    root BIGINT NOT NULL REFERENCES roots(id) ON DELETE CASCADE,
    relative_path TEXT NOT NULL,
    computer TEXT NOT NULL REFERENCES computers(id) ON DELETE CASCADE,
    path TEXT NOT NULL,
    PRIMARY KEY(root, relative_path, computer)
);
